### ISSUE TITLE
Suggestion for setup_json(json)

### ISSUE THREAD

**Issue by devster31** [mapio/nofussbm#5]
In the `api.py` [here](https://github.com/mapio/nofussbm/blob/0067bf2b21f57a85d79d4908f64b15e1073c1db7/nofussbm/api.py#L38) and `helper.py` file [here](https://github.com/mapio/nofussbm/blob/0067bf2b21f57a85d79d4908f64b15e1073c1db7/nofussbm/helpers.py#L51) a function to use a custom JSON Encoder and Decoder is defined and called. I noticed that Flask has a `class flask.json.JSONDecoder` and `class flask.json.JSONEncoder` but also allows for `app.json_decoder = MyCustomJSONDecoder` to be defined, so to make it less hackish something like this could be done in, for example `nofussbm/json.py`:
```python
from flask.json import JSONEncoder, JSONDecoder

class NofussbmJSONEncoder(JSONEncoder):

    def default(self, obj):
        [...]
        return JSONEncoder.default(self, obj)

class NofussbmJSONDecoder(JSONDecoder):

    def __init__(self, *args, **kwargs):
        self.orig_object_hook = kwargs.pop("object_hook", None)
        super(NofussbmJSONDecoder, self).__init__(*args, object_hook=self.custom_object_hook, **kwargs)

    def custom_object_hook(self, dct):
        [...]
```
and then in `nofussbm/__init__.py`:
```
from .json import NofussbmJSONEncoder, NofussbmJSONDecoder
app.json_encoder = NofussbmJSONEncoder
app.json_decoder = NofussbmJSONDecoder
```

**Comment by mapio** [comment]
This makes sense! Would you like to implement and test it so that I can merge it? 

I'm out of my office now, in case you can't do it yourself I'll take care next week.

**Comment by devster31** [comment]
I tried to do it in #6 , the reference in the title wasn't picked up.

**Comment by mapio** [comment]
Thanks a lot for you effort. As soon as I'll have time to double check it I'll merge the request!
