### ISSUE TITLE
Documentation for Installation

### ISSUE THREAD

**Issue by Okeanos** [mapio/nofussbm#8]
I am currently evaluating self-hosted bookmark management software and stumbled upon nofussbm, however, I am a little disappointed in the lack of documentation pertaining to installation, maintenance, and configuration. Would it be possible to provide a documentation that lists among others:

* Requirements (system requirements that have to be (manually) installed)
* Installation steps
* Configuration options (acceptable values & defaults)
* Upgrade instructions if applicable (such as DB migrations)
* API documentation such as [Swagger](http://swagger.io) or similar

I think this project would profit greatly from some expanded documentation and a basic usage instruction set, especially for people like myself who would simply give it a try locally without delving too deeply into the code.

**Comment by mapio** [comment]
Unfortunately I don't have the time to write such documentation at present time. 

I agree that the project would benefit from it, and I'm sorry that you are disappointed that a free open source project does not meet your expectations. 

I would be grateful to accept a pull request from you if you'll ever find the time to provide the suggested documentation.
